theme: jekyll-theme-minimal
title: AI-WORKSPACE
description: Multi-Agent Collaboration System
show_downloads: false
google_analytics: 
github:
  is_project_page: true
  repository_url: https://github.com/manwonyori/-AI-WORKSPACE
  repository_name: AI-WORKSPACE